title: Marcel Cremer
description: >
  Full Stack Dev, Consultant, Game Addict
copyright: Marcel Cremer
sass:
  sass_dir: assets/sass
url: https://marcel-cremer.de
? disqus_shortname: stratajekylldemo
? facebook_username
twitter_username: "ma_cremer"
? linkedin_username: "#"
? instagram_username
? pinterest_username
? flickr_username
github_username: "marcelcremer"
feed_icon: rss
email: "hello@marcel-cremer.de"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
